---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: nsm-workloads
spec:
  spiffeIDTemplate: ""
  podSelector:
    matchLabels:
      "spiffe.io/spiffe-id": "true"
  federatesWith: []
