---
apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire
  annotations:
    metallb.universe.tf/address-pool: my-ip-pool
spec:
  type: LoadBalancer
  selector:
    app: spire-server
  ports:
    - name: spire-server
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: bundle-endpoint
      port: 8443
      targetPort: 8443
      protocol: TCP